### ISSUE TITLE
Broken with latest Ember release

### ISSUE THREAD

**Issue by alexlafroscia** [Ravenstine/ember-custom-elements#13]
It seems that this addon is not compatible with the latest Ember release; consume arguments within the component isn't working correctly.

I'm going to investigate a fix, but figure I would post an issue in case anyone else also gets bitten by this!

**Comment by Ravenstine** [comment]
I'll take a look at this soon.

**Comment by Ravenstine** [comment]
@alexlafroscia I've made a new release(v2.0.4) that fixes the add-on for the latest Ember LTS through Canary.

**Comment by Ravenstine** [comment]
Closing this since tests now pass with LTS, beta, current, and canary.  I'll see about running Travis periodically so breakages can be caught sooner.

**Comment by alexlafroscia** [comment]
Sorry, I mean to comment on this a few days ago! I tested your fix in our app and it did indeed resolve the problem we were seeing[
